### ISSUE TITLE
redmine_issue_priority_alert vs Redmine 3.4.4.

### ISSUE THREAD

**Issue by dripfeeder** [southbridgeio/redmine_issue_priority_alert#1]
Здравствуйте.
Я правильно понимаю, что в версии 3.4.x , да и вообще в 3 не работает?

**Comment by olemskoi** [comment]
Мы не пробовали. Используем redmine_intouch для подобных целей.

**Comment by dripfeeder** [comment]
Спасибо

**Comment by olemskoi** [comment]
Стоп. Я все перепутал. Используем и работает.

**Comment by dripfeeder** [comment]
Если позволите, то есть такое:

> Environment:
>   Redmine version                3.4.4.stable
>   Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
>   Rails version                  4.2.8
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Subversion                     1.9.5
>   Git                            2.11.0
>   Filesystem                     
> Redmine plugins:
>   redmine_contacts               4.1.2
>   redmine_issue_priority_alert   0.0.1
>   redmine_lightbox2              0.4.3

Залил плагин, сделал `rake redmine:plugins:migrate RAILS_ENV=production`, рестартанул apache, но не работет.  В redmine (в модулях) отображается как надо.  С 14 года используем, решили обновиться и  печаль вот)

**Comment by olemskoi** [comment]
Возможно есть что-то в логах крон?

**Comment by dripfeeder** [comment]
Вообще ничего нет.  Убрали да же кастомную тему, с лефолтной то же самое.  Ну ладно, значит что-то мы косячим.
